force-app/main/default/objects/Objective__c/Objective__c.object-meta.xml
<CustomObject>
    <label>Objective</label>
    <nameField>
        <label>Objective Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Objectives</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Objective__c/fields/User__c.field-meta.xml
<CustomField>
    <fullName>User__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>User</label>
    <referenceTo>User</referenceTo>
    <relationshipName>Objectives</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/Apex Classes/displayObjectiveController.cls
public with sharing class displayObjectiveController {
    @AuraEnabled(cacheable=true)
    public static List<Objective__c> getObjective(String userId) {
        List<Objective__c> objectives = new List<Objective__c>();
        try {
            objectives = [SELECT Name, Id FROM Objective__c WHERE User__c = :userId];
        } catch (Exception e) {
            System.debug('Error: ' + e.getMessage());
            throw new AuraHandledException('An error occurred while fetching objectives.');
        }
        return objectives;
    }
}